// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CmdAuctionRisePrice.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AuctionWar {

  /// <summary>Holder for reflection information generated from CmdAuctionRisePrice.proto</summary>
  public static partial class CmdAuctionRisePriceReflection {

    #region Descriptor
    /// <summary>File descriptor for CmdAuctionRisePrice.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CmdAuctionRisePriceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlDbWRBdWN0aW9uUmlzZVByaWNlLnByb3RvEgpBdWN0aW9uV2FyIiIKE0Nt",
            "ZEF1Y3Rpb25SaXNlUHJpY2USCwoDZ2FwGAEgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AuctionWar.CmdAuctionRisePrice), global::AuctionWar.CmdAuctionRisePrice.Parser, new[]{ "Gap" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CmdAuctionRisePrice : pb::IMessage<CmdAuctionRisePrice> {
    private static readonly pb::MessageParser<CmdAuctionRisePrice> _parser = new pb::MessageParser<CmdAuctionRisePrice>(() => new CmdAuctionRisePrice());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CmdAuctionRisePrice> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AuctionWar.CmdAuctionRisePriceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CmdAuctionRisePrice() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CmdAuctionRisePrice(CmdAuctionRisePrice other) : this() {
      gap_ = other.gap_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CmdAuctionRisePrice Clone() {
      return new CmdAuctionRisePrice(this);
    }

    /// <summary>Field number for the "gap" field.</summary>
    public const int GapFieldNumber = 1;
    private int gap_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Gap {
      get { return gap_; }
      set {
        gap_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CmdAuctionRisePrice);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CmdAuctionRisePrice other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Gap != other.Gap) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Gap != 0) hash ^= Gap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Gap != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Gap);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Gap != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gap);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CmdAuctionRisePrice other) {
      if (other == null) {
        return;
      }
      if (other.Gap != 0) {
        Gap = other.Gap;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Gap = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
