// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CmdPutInMaterial.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AuctionWar {

  /// <summary>Holder for reflection information generated from CmdPutInMaterial.proto</summary>
  public static partial class CmdPutInMaterialReflection {

    #region Descriptor
    /// <summary>File descriptor for CmdPutInMaterial.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CmdPutInMaterialReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZDbWRQdXRJbk1hdGVyaWFsLnByb3RvEgpBdWN0aW9uV2FyIjwKEENtZFB1",
            "dEluTWF0ZXJpYWwSEgoKc3RvcmVob3VzZRgBIAEoBRIUCgxwcm9jZXNzYmxv",
            "Y2sYAiABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AuctionWar.CmdPutInMaterial), global::AuctionWar.CmdPutInMaterial.Parser, new[]{ "Storehouse", "Processblock" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CmdPutInMaterial : pb::IMessage<CmdPutInMaterial> {
    private static readonly pb::MessageParser<CmdPutInMaterial> _parser = new pb::MessageParser<CmdPutInMaterial>(() => new CmdPutInMaterial());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CmdPutInMaterial> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AuctionWar.CmdPutInMaterialReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CmdPutInMaterial() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CmdPutInMaterial(CmdPutInMaterial other) : this() {
      storehouse_ = other.storehouse_;
      processblock_ = other.processblock_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CmdPutInMaterial Clone() {
      return new CmdPutInMaterial(this);
    }

    /// <summary>Field number for the "storehouse" field.</summary>
    public const int StorehouseFieldNumber = 1;
    private int storehouse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Storehouse {
      get { return storehouse_; }
      set {
        storehouse_ = value;
      }
    }

    /// <summary>Field number for the "processblock" field.</summary>
    public const int ProcessblockFieldNumber = 2;
    private int processblock_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Processblock {
      get { return processblock_; }
      set {
        processblock_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CmdPutInMaterial);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CmdPutInMaterial other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Storehouse != other.Storehouse) return false;
      if (Processblock != other.Processblock) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Storehouse != 0) hash ^= Storehouse.GetHashCode();
      if (Processblock != 0) hash ^= Processblock.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Storehouse != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Storehouse);
      }
      if (Processblock != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Processblock);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Storehouse != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Storehouse);
      }
      if (Processblock != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Processblock);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CmdPutInMaterial other) {
      if (other == null) {
        return;
      }
      if (other.Storehouse != 0) {
        Storehouse = other.Storehouse;
      }
      if (other.Processblock != 0) {
        Processblock = other.Processblock;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Storehouse = input.ReadInt32();
            break;
          }
          case 16: {
            Processblock = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
